CREATE TABLE TB_ACAO_CONTROLE (
  ID_ACAO_CONTROLE BIGSERIAL PRIMARY KEY,
  TITULO VARCHAR(200) NOT NULL
);

CREATE TABLE TB_ORDEM_SERVICO (
  ID_ORDEM_SERVICO BIGSERIAL PRIMARY KEY,
  ID_ACAO_CONTROLE BIGINT NOT NULL REFERENCES TB_ACAO_CONTROLE(ID_ACAO_CONTROLE),
  NOME_TEMPLATE VARCHAR(120) NOT NULL,
  DESCRICAO TEXT,
  RESPONSAVEL VARCHAR(120)
);

-- índices úteis
CREATE INDEX IX_OS_ACAO ON TB_ORDEM_SERVICO(ID_ACAO_CONTROLE);
