CREATE TABLE IF NOT EXISTS TB_ASSINATURA (
  ID_ASSINATURA       BIGSERIAL PRIMARY KEY,
  ID_ORDEM_SERVICO    BIGINT      NOT NULL,
  NOME_ARQUIVO        VARCHAR(255) NOT NULL,
  HASH_SHA256         CHAR(64)     NOT NULL,
  CONTEUDO            BYTEA        NOT NULL,   -- H2 aceita BLOB/VARBINARY; Postgres usa BYTEA
  GERADO_EM           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Campos futuros (assinatura digital). Pode deixar agora como NULL:
  ASSINADO_EM         TIMESTAMP,
  ASSINADO_POR        VARCHAR(150),

  CONSTRAINT FK_ASSINATURA_OS
    FOREIGN KEY (ID_ORDEM_SERVICO)
    REFERENCES TB_ORDEM_SERVICO (ID_ORDEM_SERVICO)
);